Blacklist pbr 3.1.1 from setup
Pbr release 3.1.1 is broken and causes problems with install via pip if
it is used, so make sure to prevent it being used.

Pbr 3.1.1 will result in the following error during a pip install:

  TypeError: super() argument 1 must be type, not None

fixes: #14